
services:
  node_app:
    build: .
    # image: node_pgsql-node_app:latest
    volumes:
      - /etc/ssl/certs/si-10.cen-champagne-ardenne.org:/etc/ssl/certs/si-10.cen-champagne-ardenne.org:ro
      - /mnt/storage_data/app/:/mnt/storage_data/app/
    ports:
      - "8889:8887"
    networks:
      - monitoring
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus_data:/prometheus
    ports:
      - "9090:9090"
    networks:
      - monitoring
    restart: unless-stopped

networks:
  monitoring:
    driver: bridge