global:
  scrape_interval: 60s

scrape_configs:
  - job_name: 'nodejs_app'
    scheme: https
    tls_config:
      insecure_skip_verify: true  # Ignore la vérification du certificat
    static_configs:
      - targets: ['node_app:8887']

  # - job_name: 'conserv'
  #   static_configs:
  #     - targets: ['localhost:9100']